import { createClient } from '@supabase/supabase-js';

const s = createClient(
  'https://ybbepmotbitjrpsvsics.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliYmVwbW90Yml0anJwc3ZzaWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwMTU2MzksImV4cCI6MjA5NjU5MTYzOX0.iuJu5TUHQ3TdQb5hCSqb_Ie3XGOa5f2V_IWRPoTn77g'
);

const skills = [
  {slug:'superpowers-tdd',name:'TDD 测试驱动开发',cat:'编程开发',author:'obra',desc:'先写测试，再写实现，红绿重构循环。帮AI写出有测试保障的代码。',install:'git clone https://github.com/obra/superpowers.git',repo:'https://github.com/obra/superpowers',gh:'obra',content:'测试驱动开发完整工作流：红→绿→重构循环。先写测试用例，再实现功能代码，最后重构优化。每次只做最小的改动，保持测试通过。'},
  {slug:'superpowers-debug',name:'系统化调试方法',cat:'编程开发',author:'obra',desc:'遇到Bug不瞎猜：观察现象、形成假设、设计实验、二分法定位根因。',install:'git clone https://github.com/obra/superpowers.git',repo:'https://github.com/obra/superpowers',gh:'obra',content:'系统化调试步骤：1.复现Bug并记录现象 2.形成可能的原因假设 3.设计最小实验验证假设 4.二分法缩小范围 5.找到根因后修复并加回归测试。'},
  {slug:'superpowers-review',name:'代码审查助手',cat:'编程开发',author:'obra',desc:'AI审查代码：逻辑错误、安全问题、性能隐患、可维护性。给出具体修改建议和示例。',install:'git clone https://github.com/obra/superpowers.git',repo:'https://github.com/obra/superpowers',gh:'obra',content:'代码审查维度：正确性、安全性、性能、可读性、可维护性。对每处问题标明严重等级，给出修复建议和示例代码。'},
  {slug:'stream-coding',name:'Stream Coding 方法论',cat:'编程开发',author:'frmoretto',desc:'告别Vibe Coding，用10-20倍效率的Stream Coding方法进行AI辅助开发。先思考再编码。',install:'git clone https://github.com/frmoretto/stream-coding.git',repo:'https://github.com/frmoretto/stream-coding',gh:'frmoretto',content:'Stream Coding核心原则：先思考再编码、一次只做一件事、保持代码简洁、不断测试验证。AI是你的加速器而非替代品。'},
  {slug:'code-cleanup',name:'代码清理与重构',cat:'编程开发',author:'Hao0321',desc:'扫描代码库：重复代码、命名不规范、可模块化块、过大文件、未使用代码。',install:'git clone https://github.com/Hao0321/claude-skill-code-cleanup.git',repo:'https://github.com/Hao0321/claude-skill-code-cleanup',gh:'Hao0321',content:'代码清理检查清单：重复代码检测、命名规范检查、模块化建议、文件大小分析、未使用代码查找。每项给出优先级和修复示例。'},
  {slug:'skill-creator',name:'Skill 创建器',cat:'编程开发',author:'Anthropic',desc:'把重复工作流变成可复用 SKILL.md。描述流程，AI生成标准格式skill文件。',install:'git clone https://github.com/anthropics/skills.git',repo:'https://github.com/anthropics/skills',gh:'anthropics',content:'Skill创建流程：描述工作流→确定触发条件→拆解步骤→编写SKILL.md→测试→优化。生成的skill包含name、description、工作流步骤和参考文件。'},
  {slug:'planning-files',name:'文件式任务规划',cat:'编程开发',author:'OthmanAdi',desc:'用Markdown持久化复杂任务规划，断点续传不怕崩溃。多Agent共享状态。',install:'git clone https://github.com/OthmanAdi/planning-with-files.git',repo:'https://github.com/OthmanAdi/planning-with-files',gh:'OthmanAdi',content:'文件式规划法：task_plan.md→findings.md→progress.md。任务崩溃后从文件恢复，多Agent协同读写。确定性完成门控，不丢进度。'},
  {slug:'writing-style',name:'写作风格学习器',cat:'论文写作',author:'jzOcb',desc:'AI写作→你修改→规则自动提取→SKILL.md自动优化。越用越懂你的写作风格。',install:'git clone https://github.com/jzOcb/writing-style-skill.git',repo:'https://github.com/jzOcb/writing-style-skill',gh:'jzOcb',content:'写作风格自学习：你修改AI输出后，系统自动提取修改规律，更新SKILL.md中的写作规则。包括句式偏好、用词习惯、格式要求等。'},
  {slug:'git-worktree',name:'Git Worktree 隔离开发',cat:'编程开发',author:'obra',desc:'用Git Worktree在隔离环境开发新功能，不干扰主工作区。多人并行互不冲突。',install:'git clone https://github.com/obra/superpowers.git',repo:'https://github.com/obra/superpowers',gh:'obra',content:'Git Worktree：为每个功能/修复创建独立worktree→隔离开发→完成后合并→清理。避免分支切换导致的文件混乱和上下文丢失。'},
  {slug:'pm-skills',name:'产品经理技能包',cat:'求职就业',author:'mohitagw15856',desc:'167个PM专业技能：PRD撰写、竞品分析、用户故事、需求排序、路线图规划。',install:'git clone https://github.com/mohitagw15856/pm-claude-skills.git',repo:'https://github.com/mohitagw15856/pm-claude-skills',gh:'mohitagw15856',content:'PM核心技能：PRD模板、竞品分析框架、用户故事地图、KANO模型、ROI评估、A/B测试设计、产品路线图规划。涵盖18个职业方向的167个技能。'},
  {slug:'nuxt-skills',name:'Vue/Nuxt 开发技能',cat:'编程开发',author:'onmax',desc:'Vue3+Nuxt3+NuxtHub全栈：组件设计、状态管理、SSR、API路由、服务端渲染。',install:'git clone https://github.com/onmax/nuxt-skills.git',repo:'https://github.com/onmax/nuxt-skills',gh:'onmax',content:'Nuxt开发最佳实践：Composition API、useFetch/useAsyncData、服务端路由、中间件、插件系统、NuxtHub部署。每个组件有类型定义和错误处理。'},
  {slug:'design-md',name:'设计系统生成器',cat:'其他',author:'bergside',desc:'从Figma提取设计规范→生成DESIGN.md→AI按规范写界面。颜色/字体/间距/组件。',install:'git clone https://github.com/bergside/design-md-figma.git',repo:'https://github.com/bergside/design-md-figma',gh:'bergside',content:'设计系统提取：从Figma导出颜色、字体、间距、组件→生成DESIGN.md→AI按照设计规范生成界面代码。支持暗色模式、响应式断点配置。'},
  {slug:'ros2-skills',name:'ROS2 机器人开发',cat:'编程开发',author:'dbwls99706',desc:'ROS2生产级开发：节点/执行器/QoS/ros2_control/Nav2导航/MoveIt2机械臂。',install:'git clone https://github.com/dbwls99706/ros2-engineering-skills.git',repo:'https://github.com/dbwls99706/ros2-engineering-skills',gh:'dbwls99706',content:'ROS2开发指南：workspace结构、节点生命周期、QoS配置、launch文件、参数管理、TF2坐标变换、ros2_control硬件抽象、Nav2导航栈、MoveIt2运动规划。'},
  {slug:'research-skills',name:'学术研究助手',cat:'论文写作',author:'WenyuChiou',desc:'文献综述、研究设计、论文写作、跨Agent协作。覆盖从选题到发表的完整科研流程。',install:'git clone https://github.com/WenyuChiou/ai-research-skills.git',repo:'https://github.com/WenyuChiou/ai-research-skills',gh:'WenyuChiou',content:'学术研究流程：文献检索与综述、研究问题定义、实验设计、数据收集与分析、论文写作、同行评审回应。每步有模板和检查清单。'},
  {slug:'office-excel',name:'Excel 金融建模',cat:'求职就业',author:'fivetaku',desc:'DCF估值、LBO建模、三张表联动、可比公司分析。投行面试必备，专业金融建模。',install:'git clone https://github.com/fivetaku/claude-office-skills.git',repo:'https://github.com/fivetaku/claude-office-skills',gh:'fivetaku',content:'金融建模技能：DCF估值(FCF预测→WACC→终值→股权价值)、LBO模型(收购→债务→退出回报)、三张报表联动(I/S→B/S→CFS)、可比公司分析。'},
  {slug:'office-ppt',name:'PPT 演示文稿生成',cat:'求职就业',author:'fivetaku',desc:'专业PPT：麦肯锡金字塔结构、图表最佳实践、数据驱动叙事、演讲备注。',install:'git clone https://github.com/fivetaku/claude-office-skills.git',repo:'https://github.com/fivetaku/claude-office-skills',gh:'fivetaku',content:'PPT制作：麦肯锡金字塔结构、图表最佳实践(bar/line/waterfall)、数据驱动叙事、每页一个核心信息、演讲备注撰写、模板一致性检查。'},
  {slug:'founder-skills',name:'创业者工具包',cat:'求职就业',author:'ognjengt',desc:'20+创业技能：商业计划书、融资Pitch、市场分析、用户调研、MVP规划、增长实验。',install:'git clone https://github.com/ognjengt/founder-skills.git',repo:'https://github.com/ognjengt/founder-skills',gh:'ognjengt',content:'创业必备：商业计划书模板(问题→方案→市场→团队→财务)、投资人Pitch脚本、精益画布、用户访谈框架、MVP优先级矩阵、增长实验设计。'},
  {slug:'tailwind-ui',name:'Tailwind UI 组件生成',cat:'编程开发',author:'mxyhi',desc:'Tailwind CSS快速生成UI组件。暗色模式、响应式、无障碍访问、动画效果。',install:'git clone https://github.com/mxyhi/ok-skills.git',repo:'https://github.com/mxyhi/ok-skills',gh:'mxyhi',content:'Tailwind组件开发：shadcn/ui风格组件、响应式断点(sm/md/lg/xl)、暗色模式(dark:)、无障碍(aria-*)、动画(transition/animate)、布局(grid/flex)。'},
  {slug:'nextjs-skills',name:'Next.js 全栈开发',cat:'编程开发',author:'mxyhi',desc:'Next.js 14+ App Router最佳实践：Server Components、Route Handlers、Server Actions。',install:'git clone https://github.com/mxyhi/ok-skills.git',repo:'https://github.com/mxyhi/ok-skills',gh:'mxyhi',content:'Next.js最佳实践：App Router路由结构、Server/Client组件边界、数据获取(cache/revalidate)、Server Actions表单处理、Middleware鉴权、ISR/SSG策略。'},
  {slug:'docker-skills',name:'Docker 容器化部署',cat:'编程开发',author:'mxyhi',desc:'Dockerfile编写、docker-compose编排、多阶段构建、镜像优化。从开发到生产。',install:'git clone https://github.com/mxyhi/ok-skills.git',repo:'https://github.com/mxyhi/ok-skills',gh:'mxyhi',content:'Docker实践：多阶段构建减小镜像、layer缓存优化、docker-compose服务编排、环境变量管理、健康检查、日志收集、CI/CD集成。'},
  {slug:'api-design',name:'RESTful API 设计',cat:'编程开发',author:'mxyhi',desc:'API设计最佳实践：命名规范、版本管理、错误处理、分页、认证授权。OpenAPI文档。',install:'git clone https://github.com/mxyhi/ok-skills.git',repo:'https://github.com/mxyhi/ok-skills',gh:'mxyhi',content:'API设计规范：资源命名(复数名词)、HTTP方法语义(GET/POST/PUT/DELETE)、状态码选择、分页(cursor/offset)、错误格式(RFC 7807)、认证(Bearer/JWT)、OpenAPI文档生成。'},
  {slug:'db-design',name:'数据库设计与优化',cat:'编程开发',author:'mxyhi',desc:'关系型数据库设计：范式化、索引优化、查询性能分析、迁移管理。MySQL/PostgreSQL。',install:'git clone https://github.com/mxyhi/ok-skills.git',repo:'https://github.com/mxyhi/ok-skills',gh:'mxyhi',content:'数据库设计：ER图→表结构、范式化(3NF)、索引策略(B-tree/Hash/GIN)、慢查询分析(EXPLAIN)、连接池配置、迁移文件管理、数据备份策略。'},
  {slug:'python-data',name:'Python 数据分析',cat:'编程开发',author:'frankxai',desc:'Pandas/NumPy/Matplotlib数据分析：清洗、统计、可视化、报告生成。Jupyter友好。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'数据分析流程：数据读取(pd.read_csv/excel/sql)→数据清洗(缺失值/异常值/类型转换)→探索性分析(describe/groupby/pivot)→可视化(plt/seaborn)→结论报告。'},
  {slug:'react-patterns',name:'React 设计模式',cat:'编程开发',author:'frankxai',desc:'React高级模式：Compound Components、HOC、Custom Hooks、Provider模式。含代码示例。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'React设计模式详解：Compound Component(共享状态)、Custom Hook(逻辑复用)、HOC(属性注入)、Provider/Context(全局状态)、Render Props(渲染委托)。每种附代码示例。'},
  {slug:'git-workflow',name:'Git 协作工作流',cat:'编程开发',author:'frankxai',desc:'GitFlow/GitHubFlow/TrunkBased——分支策略、PR review规范、冲突解决、commit规范。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'Git协作规范：分支命名(feat/fix/chore)、commit message(conventional commits)、PR模板、Code Review清单、冲突解决策略、git rebase vs merge选择。'},
  {slug:'solidity-audit',name:'Solidity 智能合约审计',cat:'编程开发',author:'sanbir',desc:'210种智能合约攻击向量和审计检查。DeFi安全必备：重入、闪电贷、预言机操纵。',install:'git clone https://github.com/sanbir/solidity-auditor-skills.git',repo:'https://github.com/sanbir/solidity-auditor-skills',gh:'sanbir',content:'智能合约审计清单：重入攻击、整数溢出、访问控制、前端运行、闪电贷攻击、预言机操纵、存储碰撞、未初始化代理。每个漏洞含检测脚本和修复建议。'},
  {slug:'webgpu-skills',name:'WebGPU 图形编程',cat:'编程开发',author:'dgreenheck',desc:'WebGPU+Three.js TSL：GPU计算、渲染管线、着色器编程。浏览器端高性能3D图形。',install:'git clone https://github.com/dgreenheck/webgpu-claude-skill.git',repo:'https://github.com/dgreenheck/webgpu-claude-skill',gh:'dgreenheck',content:'WebGPU入门：设备初始化→管线→缓冲区→WGSL着色器→渲染通道→计算着色器。与Three.js TSL集成，GPU粒子系统、后处理效果。'},
  {slug:'godot-skills',name:'Godot 游戏开发',cat:'编程开发',author:'htdt',desc:'从描述生成Godot 4项目：场景搭建、脚本编写、资源导入、导出打包。GDScript/C#。',install:'git clone https://github.com/htdt/godogen.git',repo:'https://github.com/htdt/godogen',gh:'htdt',content:'Godot开发：GDScript/C#脚本、节点系统、信号机制、场景实例化、物理引擎、UI系统、动画树、资源管道、导出配置(Web/Mobile/Desktop)。'},
  {slug:'postgres-optimize',name:'PostgreSQL 性能优化',cat:'编程开发',author:'frankxai',desc:'PG性能调优：执行计划分析、索引策略、查询重写、Vacuum配置、连接池管理。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'PG优化：EXPLAIN ANALYZE解读、统计信息(pg_stat_user_tables)、索引类型选择、分区表、物化视图、pgBouncer配置、autovacuum调优、work_mem/shared_buffers设置。'},
  {slug:'leetcode-helper',name:'算法刷题助手',cat:'考试备考',author:'frankxai',desc:'LeetCode/牛客刷题：理解题意→分析复杂度→多种解法→代码实现→测试用例。含模板。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'刷题方法论：理解题意、暴力解法→分析瓶颈、优化(空间换时间/数学性质/数据结构)、实现+边界测试、复杂度分析。模板：双指针/滑动窗口/DP/图遍历/回溯。'},
  {slug:'system-design',name:'系统设计面试',cat:'求职就业',author:'frankxai',desc:'系统设计面试：设计Twitter/WhatsApp/YouTube。容量估算、数据库选型、架构图。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'系统设计框架：需求澄清(功能/非功能)→容量估算(QPS/存储/带宽)→API设计→数据库选型(SQL/NoSQL)→架构图→深入讨论(扩展/一致性/容错)。经典题目详解。'},
  {slug:'cv-optimize',name:'简历深度优化',cat:'求职就业',author:'frankxai',desc:'精准优化简历：ATS关键词匹配、STAR量化成果包装、一页纸排版。技术/产品/咨询岗。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'简历优化：JD关键词提取→经历STAR改写→量化数据补充→排版(一页/层次/留白)→ATS兼容性检查→中英文双版。涵盖技术/产品/运营/咨询岗位模板。'},
  {slug:'interview-prep',name:'面试模拟训练',cat:'求职就业',author:'frankxai',desc:'AI模拟面试官：行为面试(STAR)、技术面试、案例分析。实时反馈和改进建议。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'面试训练：行为面试(领导力/冲突解决/失败经历)、技术面试(算法/系统设计/项目深挖)、自我介绍公式(现在→过去→未来)、反问环节问题清单、面试后复盘模板。'},
  {slug:'marketing-copy',name:'营销文案写作',cat:'求职就业',author:'frankxai',desc:'小红书/公众号/抖音文案：标题技巧、卖点提炼、CTA设计、A/B测试方案。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'文案方法论：AIDA模型(注意→兴趣→欲望→行动)、4P卖点提炼、FAB法则(特征→优势→利益)、标题公式(数字+痛点+解决方案)、CTA按钮设计、不同平台文案风格适配。'},
  {slug:'finance-stmt',name:'财务报表分析',cat:'求职就业',author:'himself65',desc:'三张报表深度分析：杜邦分析、现金流质量、盈利质量、估值比率。CFA/CPA备考。',install:'git clone https://github.com/himself65/finance-skills.git',repo:'https://github.com/himself65/finance-skills',gh:'himself65',content:'财报分析框架：利润表(收入质量/利润率趋势)、资产负债表(杠杆/流动性/资产质量)、现金流量表(经营/投资/筹资)。关键比率：ROE/ROA/Current Ratio/D/E/P/E/P/B。'},
  {slug:'cfa-prep',name:'CFA 备考助手',cat:'考试备考',author:'himself65',desc:'CFA一二三级备考：知识点梳理、公式速查、错题分析、模拟考试。金融计算器使用。',install:'git clone https://github.com/himself65/finance-skills.git',repo:'https://github.com/himself65/finance-skills',gh:'himself65',content:'CFA备考：十大科目知识框架、核心公式速查表、道德准则(Standards I-VII)、计算题步骤详解(NPV/IRR/Duration/Convexity)、模考成绩分析→薄弱点定位。'},
  {slug:'ml-crashcourse',name:'机器学习速成',cat:'编程开发',author:'frankxai',desc:'ML入门到实战：数据预处理、模型选择、训练调参、评估部署。Sklearn/PyTorch。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'ML流程：数据EDA→特征工程→模型选择(分类/回归/聚类)→交叉验证→超参调优(Grid/Random/Bayesian)→模型解释(SHAP/LIME)→部署(ONNX/Flask)。含代码模板。'},
  {slug:'deep-learning',name:'深度学习实战',cat:'编程开发',author:'frankxai',desc:'PyTorch深度学习：CNN/RNN/Transformer/GAN。训练技巧、分布式、混合精度。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'DL实战：DataLoader/Dataset、nn.Module定义、训练循环(optimizer/scheduler/loss)、验证与早停、TensorBoard可视化、混合精度训练(AMP)、分布式(DDP)配置。'},
  {slug:'web-scraping',name:'网页爬虫与数据采集',cat:'编程开发',author:'frankxai',desc:'Python爬虫：Requests/Scrapy/Playwright。反爬对抗、数据解析、存储、分布式。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'爬虫技能：HTTP请求头伪装、Cookie/Session管理、动态渲染(Playwright/Selenium)、XPath/CSS选择器、反爬策略(IP代理/频率控制/验证码)、数据管道(pandas→CSV/DB)。'},
  {slug:'devops-ci',name:'CI/CD 持续集成部署',cat:'编程开发',author:'mxyhi',desc:'GitHub Actions/GitLab CI：自动化测试→构建→部署流水线。Docker+K8s+Helm。',install:'git clone https://github.com/mxyhi/ok-skills.git',repo:'https://github.com/mxyhi/ok-skills',gh:'mxyhi',content:'CI/CD实战：GitHub Actions工作流(lint→test→build→deploy)、多环境配置(dev/staging/prod)、Docker镜像构建推送、K8s部署(Deployment/Service/Ingress)、Helm chart管理。'},
  {slug:'typescript-utils',name:'TypeScript 工具类型',cat:'编程开发',author:'frankxai',desc:'TS高级类型：Utility Types、条件类型、模板字面量、类型推断。类型体操进阶。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'TS类型进阶：Partial/Required/Pick/Omit/Exclude/Extract、条件类型(T extends U)、infer关键字、模板字面量类型、映射类型、递归类型、品牌类型。'},
  {slug:'pythonic-code',name:'Pythonic 代码之道',cat:'编程开发',author:'frankxai',desc:'写出地道Python：列表推导、生成器、装饰器、上下文管理器、dataclass、类型注解。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'Pythonic实践：list/dict/set comprehension、generator(yield)、@property/@staticmethod、with/contextlib、@dataclass、Type Hints(mypy)、functools(lru_cache/partial)、itertools妙用。'},
  {slug:'linux-shell',name:'Linux Shell 脚本',cat:'编程开发',author:'mxyhi',desc:'Bash/Zsh脚本：文本处理(awk/sed/grep)、进程管理、定时任务、系统监控、日志分析。',install:'git clone https://github.com/mxyhi/ok-skills.git',repo:'https://github.com/mxyhi/ok-skills',gh:'mxyhi',content:'Shell脚本：变量/数组/函数/参数、条件判断(test/[[]])、循环(for/while)、文本三剑客(grep/sed/awk)、cron定时任务、进程管理(ps/top/kill)、系统信息(cpu/mem/disk)、日志分析。'},
  {slug:'prisma-orm',name:'Prisma ORM 最佳实践',cat:'编程开发',author:'frankxai',desc:'Prisma数据库：Schema设计、Migration管理、关系查询、事务处理、性能优化。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'Prisma技巧：relation(1-1/1-N/N-N)、嵌套查询(include/select)、filter/sort/pagination、interactive transaction、raw SQL、n+1问题解决、seed/migration最佳实践。'},
  {slug:'vscode-extension',name:'VS Code 插件开发',cat:'编程开发',author:'frankxai',desc:'VS Code扩展：命令、菜单、侧边栏、Webview、Language Server Protocol。发布到商店。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'VS Code扩展：package.json配置(activationEvents/contributes)、Extension API(commands/window/workspace)、TreeView侧边栏、Webview Panel、LSP实现、测试(e2e/unit)、发布商店。'},
  {slug:'flutter-widget',name:'Flutter 组件开发',cat:'编程开发',author:'frankxai',desc:'Flutter/Dart Widget：State管理(Riverpod/Bloc)、路由导航、动画、原生交互、性能优化。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'Flutter实战：Widget树(Stateless/Stateful)、状态管理(Riverpod/Bloc)、路由(Navigator 2.0)、动画(Implicit/Explicit)、Platform Channel、性能优化、测试(widget/integration)。'},
  {slug:'k8s-deploy',name:'Kubernetes 部署管理',cat:'编程开发',author:'mxyhi',desc:'K8s生产部署：Pod/Service/Ingress/ConfigMap/Secret/HPA。Helm/Kustomize管理。',install:'git clone https://github.com/mxyhi/ok-skills.git',repo:'https://github.com/mxyhi/ok-skills',gh:'mxyhi',content:'K8s实战：资源定义(YAML)、滚动更新策略、健康检查(liveness/readiness)、资源限制、自动扩缩(HPA/VPA)、ConfigMap/Secret管理、Helm Chart编写、Kustomize overlay。'},
  {slug:'redis-cache',name:'Redis 缓存策略',cat:'编程开发',author:'frankxai',desc:'Redis缓存设计：数据结构选择、过期策略、缓存模式(穿透/击穿/雪崩)、分布式锁。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'Redis最佳实践：缓存模式(Cache-Aside/Read-Through/Write-Behind)、过期策略(LRU/LFU/TTL)、缓存穿透(布隆过滤器)/击穿(互斥锁)/雪崩(随机TTL)、分布式锁(RedLock)、Stream消息队列。'},
  {slug:'rest-assured',name:'API 自动化测试',cat:'编程开发',author:'frankxai',desc:'REST API测试：Jest/Supertest/Pytest。单元测试、集成测试、契约测试、性能测试。',install:'git clone https://github.com/frankxai/claude-skills-library.git',repo:'https://github.com/frankxai/claude-skills-library',gh:'frankxai',content:'API测试策略：测试金字塔(unit→integration→e2e)、HTTP状态码验证、请求/响应Schema验证、边界条件测试、并发测试、性能测试(k6/artillery)、测试覆盖率目标。'},
];

let ok = 0, fail = 0;
for (const sk of skills) {
  const { error } = await s.from('skills').insert({
    slug: sk.slug, name: sk.name, category: sk.cat, author_name: sk.author,
    description: sk.desc, full_content: sk.content, install_command: sk.install,
    repo_url: sk.repo, author_github: sk.gh, status: 'approved',
    likes: Math.floor(Math.random() * 30), downloads: Math.floor(Math.random() * 80),
    version: '1.0.0'
  });
  if (error) { console.log('FAIL:', sk.name, error.message); fail++; }
  else { console.log('OK:', sk.name); ok++; }
}
console.log('DONE:', ok, 'ok,', fail, 'fail');
